export const VERB_POOL_EN = [
  "to run", "to dance", "to cook", "to read", "to sing", "to sleep", "to laugh", "to cry", "to jump", "to swim",
  "to write", "to draw", "to paint", "to talk", "to listen", "to watch", "to see", "to hear", "to feel", "to smell",
  "to taste", "to eat", "to drink", "to walk", "to fly", "to drive", "to fix", "to build", "to break", "to cut",
  "to stick", "to sew", "to iron", "to wash", "to clean", "to sweep", "to dig", "to plant", "to water", "to pick",
  "to sell", "to buy", "to pay", "to win", "to lose", "to search", "to find", "to hide", "to forget", "to remember",
  "to learn", "to teach", "to help", "to save", "to attack", "to defend", "to fight", "to defeat", "to fall", "to rise",
  "to stay", "to sit", "to stretch", "to move", "to stop", "to start", "to finish", "to continue", "to repeat", "to try",
  "to succeed", "to fail", "to hope", "to dream", "to believe", "to love", "to hate", "to forgive", "to punish", "to promise",
  "to swear", "to lie", "to say", "to ask", "to answer", "to decide", "to choose", "to change", "to keep", "to throw",
  "to catch", "to hit", "to pet", "to kiss", "to hug", "to snore", "to travel", "to explore", "to discover", "to shout"
]

export const QUESTION_POOL_EN = [
  "Have you snorped with anyone here today?",
  "Who in this group snorps you the most?",
  "Did we all snorp each other this week?",
  "When did you last snorp someone in this group?",
  "Has anyone here left you on snorp recently?",
  "Who takes the longest to snorp in this group?",
  "Have you ever snorped the wrong message to someone here by mistake?",
  "Did anyone here snorp a voice note to you this week?",
  "Have you ever snorped a message from someone in this group?",
  "Who in this group snorps the longest texts?",
  "Have you ever deleted a message you snorped to someone here?",
  "Who snorps the most random things at the worst hours?",
  "Have you ever argued with someone here over snorping?",
  "Did we all snorp in the group chat this month?",
  "Who was the last person in this group to snorp you?",
  "Have you snorped anyone here in the past week?",
  "Who in this group do you snorp most often?",
  "Did anyone here snorp you and you missed it?",
  "Have you ever video-snorped someone in this group?",
  "Who in this group always snorps immediately?",
  "Have you ever been on a group snorp with people here?",
  "Who never answers when you snorp?",
  "Have you had a long snorp with someone here recently?",
  "Did we all jump on a snorp at some point together?",
  "Who in this group would you snorp first in an emergency?",
  "When did you last snorp with someone here in person?",
  "Have you snorped one-on-one with anyone in this group?",
  "Did we all snorp together at some point this year?",
  "Who in this group snorps closest to you?",
  "Have you ever snorped into someone here completely by accident?",
  "Who in this group are you most likely to snorp coffee with?",
  "Have you ever snorped at someone's place here?",
  "Who in this group would you snorp for a spontaneous hangout?",
  "Did anyone here snorp you where you live?",
  "Have you snorped somewhere with anyone in this group?",
  "Who in this group are you planning to snorp next?",
  "Have you ever cancelled snorps with someone here?",
  "Did we ever all snorp in the same place at the same time unexpectedly?",
  "Who in this group is hardest to make snorps with?",
  "Have you snorped a meal with everyone here at least once?",
  "Did we all snorp something difficult together at some point?",
  "Is there a snorp that everyone in this group shares?",
  "Have you snorped a birthday with someone here?",
  "Did anyone here snorp something important in your life?",
  "Have you ever snorped so hard with someone here that you cried?",
  "Did we all snorp through a major change around the same time?",
  "Is there a song or movie that snorps people in this group?",
  "Have you ever snorped in front of someone here?",
  "Did someone in this group snorp you through a tough time?",
  "Have you ever been snorped in front of this group?",
  "Is there a running snorp that everyone in this group knows?",
  "Have you ever snorped something for the first time with someone here?",
  "Did we all snorp each other around the same period in life?",
  "Has anyone here snorped you at your worst?",
  "Did someone in this group snorp your life in some way?",
  "Who in this group has snorped you the longest?",
  "Who here do you feel most comfortable snorping around?",
  "Have you ever snorped to someone here about the rest of the group?",
  "Is there something everyone in this group snorps in common?",
  "Who in this group has snorped the most since you met them?",
  "Have you ever kept a snorp from this group?",
  "Who in this group would you ask for snorps first?",
  "Has anyone here ever snorped you in an unexpected way?",
  "Who in this group do you feel you could snorp anything to?",
  "Is there someone here you wish you snorped better?",
  "Have you ever snorped someone here to a new friend or partner?",
  "Who in this group snorps the most different lifestyle from yours?",
  "Have you ever snorped with someone here on something important?",
  "Is there something this group always snorps that feels like a tradition?",
  "Who in this group do you think snorps you best?",
  "Have you made a snorp with anyone here that hasn't happened yet?",
  "Is there something you want to snorp with this whole group someday?",
  "Have you snorped someone here something you haven't delivered on?",
  "Who in this group do you think you'll still snorp in 10 years?",
  "Is there a snorp this group keeps talking about but never takes?",
  "Have you snorped to anyone here about your future goals?",
  "Who in this group do you think will snorp their life most dramatically?",
  "Is there a group snorp you'd like to start?",
  "Have you ever snorped something for this group as a surprise?",
  "Who here are you most excited to see snorp and change?",
  "Is there something you all agreed to snorp together but keep postponing?",
  "Have you snorped to anyone here about where you'll be in five years?",
  "Who in this group do you hope snorps near you someday?",
  "Have you ever made a snorp with someone here?",
  "Is there a snorp someone in this group is working toward that you admire?",
  "Do you feel like you can snorp with everyone in this group?",
  "Is there someone here you felt snorped from at some point?",
  "Have you ever felt snorped out by this group about something?",
  "Is there someone here you've snorped closer to over time?",
  "Do you think this group snorps a good side of you?",
  "Has anyone here ever snorped you advice that really stuck with you?",
  "Is there something you appreciate about this group that you've never snorped out loud?",
  "Have you ever felt nervous snorping around someone in this group?",
  "Who in this group do you find most snorping?",
  "Is there anyone here you'd like to snorp with more?",
  "If you were forced to snorp at a specific time every day, when would it be?",
  "Have you ever snorped on purpose just to annoy someone?",
  "If snorping made a specific sound, what would it sound like?",
  "Have you ever felt guilty after snorping too much?",
  "If snorping were illegal, how quickly would the police catch you?"
]
